apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  selector:
    matchLabels:
      run: backend-user
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-user
    spec:
      containers:
        - name: backend-user
          image: docker.io/mickeyboy16/udagram-api-user:v8
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 510m
          env:
            - name: POSTGRES_USERNAME
              value: "udagrammikedev"
            - name: POSTGRES_PASSWORD
              value: "1234abcd"
            - name: POSTGRES_HOST
              value: "udagrammikedev.c9gjqoeeeukz.us-east-1.rds.amazonaws.com"
            - name: POSTGRES_DB
              value: "postgres"
