language: node_js
node_js:
  - 13

services:
  - docker

# Build and tag
script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed mickeyboy16/udagram-api-feed:v8
  
# Push
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mickeyboy16/udagram-api-feed:v9
